services:
  app:
    build: .
    container_name: gubi-server
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    volumes:
      - ./src:/app/src
    restart: unless-stopped
